spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - 'https://raw.githubusercontent.com/xndeye/adblock_list/refs/heads/release/easylist.txt' #xndeye/adblock_list
      - 'https://raw.githubusercontent.com/hululu1068/AdGuard-Rule/main/rule/all.txt'           #hululu1068/AdGuard-Rule
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt'          #hagezi/dns-blocklists-pro
     #- 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt'     ##hagezi/dns-blocklists-pro-plus
     #- 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt'     #hagezi/dns-blocklists-ultimate
     #- 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt'          #Threat Intelligence Feeds
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.medium.txt'   #Threat Intelligence Feeds-medium
      - 'https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/full/hosts.txt'                 #neohosts
      - 'https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/skyrules.txt'      #BlueSkyXN-skyrules
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
